version: "3.8"

services:
  jenkins:
    image: maven:3.9-eclipse-temurin-21
    container_name: jenkins
    ports:
      - "8282:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: